// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIxpIfSOOgRCrIekLk5W_mCMwBp-y0UIo',
    appId: '1:681708280089:web:bf272bda84253bf3338d88',
    messagingSenderId: '681708280089',
    projectId: 'derecho-en-perspectiva',
    authDomain: 'derecho-en-perspectiva.firebaseapp.com',
    storageBucket: 'derecho-en-perspectiva.firebasestorage.app',
    measurementId: 'G-M2TGTVT874',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVIhnolr5nKsB3QL6xGyagXqdtxCPGIwk',
    appId: '1:681708280089:android:7b5a77036279b1d0338d88',
    messagingSenderId: '681708280089',
    projectId: 'derecho-en-perspectiva',
    storageBucket: 'derecho-en-perspectiva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS8jWJ10XSaACY7IGTG9ADdvnRwpsFsSk',
    appId: '1:681708280089:ios:080918d1eb407c94338d88',
    messagingSenderId: '681708280089',
    projectId: 'derecho-en-perspectiva',
    storageBucket: 'derecho-en-perspectiva.firebasestorage.app',
    iosBundleId: 'com.example.derechoEnPerspectiva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS8jWJ10XSaACY7IGTG9ADdvnRwpsFsSk',
    appId: '1:681708280089:ios:080918d1eb407c94338d88',
    messagingSenderId: '681708280089',
    projectId: 'derecho-en-perspectiva',
    storageBucket: 'derecho-en-perspectiva.firebasestorage.app',
    iosBundleId: 'com.example.derechoEnPerspectiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIxpIfSOOgRCrIekLk5W_mCMwBp-y0UIo',
    appId: '1:681708280089:web:115856980b79618e338d88',
    messagingSenderId: '681708280089',
    projectId: 'derecho-en-perspectiva',
    authDomain: 'derecho-en-perspectiva.firebaseapp.com',
    storageBucket: 'derecho-en-perspectiva.firebasestorage.app',
    measurementId: 'G-WKH8LPXZLT',
  );
}
